apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - nodePort: {{ .Values.service.port }}
      targetPort: {{ .Values.nym.port }}
      protocol: TCP
      name: nym
  selector:
    {{- include "mixnode.selectorLabels" . | nindent 4 }}
