apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type | default  "LoadBalancer" }}
  ports:
    - name: nym
      port: {{ .Values.service.port | default  "8009" }}
      protocol: TCP
  selector:
    {{- include "mixnode.selectorLabels" . | nindent 4 }}
