apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mixnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mixnode.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mixnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-mixnode
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: mixnodes-config-volume
            mountPath: /root/.nym/mixnodes
          env:
          - name: INTERNAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: ["/bin/sh", "-c"]
          args:
{{ if eq .Values.environment "ci" }}
            - EXTERNAL_IP="1.2.3.4"
{{ else }}
            - EXTERNAL_IP=""
            - while [ -z $EXTERNAL_IP ]; do echo -en '\n'; export EXTERNAL_IP=$(kubectl get services | grep {{ include "mixnode.fullname" . }} | awk '{print $4}'); [ -z "$EXTERNAL_IP" ] && sleep 10; done;
{{ end }}
            - target/release/nym-mixnode init --id w3f --host $INTERNAL_IP --announce-host $EXTERNAL_IP --layer {{ .Values.nym.layer }} --location {{ .Values.nym.location }} --port 8000;
      containers:
        - name: mixnode
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: mixnodes-config-volume
            mountPath: /root/.nym-test/mixnodes
          env:
          - name: INTERNAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: nym
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: mixnodes-config-volume
        emptyDir: {}
