apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mixnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mixnode.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mixnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mixnode
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{ if eq .Values.environment "production" }}
          volumeMounts:
          - name: public-key-volume
            mountPath: /root/.nym/mixnodes/w3f/data/public_sphinx.pem
            subPath: public_sphinx.pem
            readOnly: true
          - name: private-key-volume
            mountPath: /root/.nym/mixnodes/w3f/data/private_sphinx.pem
            subPath: private_sphinx.pem
            readOnly: true
{{ end }}
          env:
          - name: INTERNAL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: ["/bin/sh", "-c"]
          args:
            - EXTERNAL_IP="";
            - while [ -z $EXTERNAL_IP ]; do echo -en '\n'; export EXTERNAL_IP=$(kubectl get services | grep {{ include "mixnode.fullname" . }} | awk '{print $4}'); [ -z "$EXTERNAL_IP" ] && sleep 10; done;
          ports:
            - name: nym
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{ if eq .Values.environment "production" }}
      volumes:
      - name: public-key-volume
        secret:
          secretName: {{ include "mixnode.fullname" . }}-public
      - name: private-key-volume
        secret:
          secretName: {{ include "mixnode.fullname" . }}-private
{{ end }}
