{{ if eq .Values.environment "production" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixnode.fullname" . }}-public
data:
  public_sphinx.pem: {{ .Values.nym.data.public_sphinx | default  "public_sphinx" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixnode.fullname" . }}-private
data:
  private_sphinx.pem: {{ .Values.nym.data.private_sphinx | default  "private_sphinx" | b64enc }}
---
{{ end }}
