{{ if eq .Values.environment "production" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixnode.fullname" . }}-public
data:
  public_sphinx.pem: {{ .Values.nym.data.public_sphinx | default  "cHVibGljX3NwaGlueAo=" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixnode.fullname" . }}-private
data:
  private_sphinx.pem: {{ .Values.nym.data.private_sphinx | default  "cHJpdmF0ZV9zcGhpbngK" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mixnode.fullname" . }}-credentials

  annotations:
    description: Provider credentials
data:
  gcp: {{ .Values.provider.credentials.gcp | default  "GCP" | b64enc }}
---
{{ end }}
