apiVersion: v1
kind: Service
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}

spec:
  type: LoadBalancer
  ports:
    - name: nym
      port: 8000
      protocol: TCP
  selector:
    {{- include "mixnode.selectorLabels" . | nindent 4 }}
