apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mixnode.fullname" . }}
  labels:
    {{- include "mixnode.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mixnode.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mixnode.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "mixnode.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-mixnode
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/root/.nym/{{ .Values.nym.id }}/config/config.toml"
            name: {{ include "mixnode.fullname" . }}-config-volume
          command: ["/bin/sh"]
          args: ["-c", "export INTERNAL_IP=$(kubectl get services | grep {{ include "mixnode.fullname" . }} | awk '{print $3}'); export EXTERNAL_IP=$(kubectl get services | grep "LoadBalancer" | awk '{print $4}'); target/release/nym-mixnode init --id {{ .Values.nym.id }} --host $INTERNAL_IP --announce-host $EXTERNAL_IP --layer {{ .Values.nym.layer }} --location {{ .Values.nym.location }} --port 8000" ]
      containers:
        - name: mixnode
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - mountPath: "/root/.nym/{{ .Values.nym.id }}/config/config.toml"
            name: {{ include "mixnode.fullname" . }}-config-volume
          command: ["/bin/sh"]
          args: ["-c", "target/release/nym-mixnode run --id {{ .Values.nym.id }}" ]
          ports:
            - name: nym
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

volumeClaimTemplates:
- metadata:
    name: {{ include "mixnode.fullname" . }}-config-volume
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 2Gi
